version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "172.22.0.1"
    volumes:
#     - ./db/mysql/data:/var/lib/mysql
#     - ./db/mysql/log:/var/log/mysql
     - ./docker/bg.sql:/docker-entrypoint-initdb.d/bg.sql:ro
#     - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf

  admin:
    image: dfang/background-manage:0.2
#    build:
#      context: ../yuanxin_admin
    container_name: admin
    restart: always
    links:
      - db:db
    ports:
      - 8888:8080


